import { Router } from "express";
import * as p from './requestHandler.js'
import Auth from "./middleware/auth.js";
const router=Router();
router.route("/signin").post(p.signIn);
router.route("/signup").post(p.signUp);
router.route("/verify").post(p.verifyMail);
router.route("/home").get(Auth,p.Home);
router.route("/seller").get(Auth,p.Seller); 
router.route("/editseller").post(Auth,p.editSeller);
router.route("/getseller").get(Auth,p.getSeller);
router.route("/addproduct").post(p.addProduct);
router.route("/getproducts").get(Auth,p.getProduct);
router.route("/adduser").post(Auth,p.addUser);
router.route("/updateuser").put(Auth,p.updateUser);
router.route("/addaddress").post(Auth,p.addAddress);
router.route("/addcat").post(p.addCategory);
router.route("/getcat").get(Auth,p.getCategory);
router.route("/getallproducts").get(Auth,p.getAllProducts);
export default router;